In [1]:
import pandas as pd

## Import module

# Load Data

In [3]:
data = pd.read_csv("..\Data\spam.csv", encoding= "latin1")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\EYAN\AppData\Local\Temp\ipykernel_11960\2168567245.py:1: SyntaxWarning: invalid escape sequence '\D'
  data = pd.read_csv("..\Data\spam.csv", encoding= "latin1")

# OBSERVE DATA

In [ ]:
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

# DROP UNNECESSARY COLUMNS

In [ ]:
data = data.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'])

In [ ]:
data

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# TURN SPAM TO 1 AND NOT TO 0

In [ ]:
data['v1'] = data['v1'].replace(
        {"ham": 0,
         "spam": 1}
)

In [ ]:
data

     v1                                                 v2
0     0  Go until jurong point, crazy.. Available only ...
1     0                      Ok lar... Joking wif u oni...
2     1  Free entry in 2 a wkly comp to win FA Cup fina...
3     0  U dun say so early hor... U c already then say...
4     0  Nah I don't think he goes to usf, he lives aro...
...  ..                                                ...
5567  1  This is the 2nd time we have tried 2 contact u...
5568  0              Will Ì_ b going to esplanade fr home?
5569  0  Pity, * was in mood for that. So...any other s...
5570  0  The guy did some bitching but I acted like i'd...
5571  0                         Rofl. Its true to its name

[5572 rows x 2 columns]

# IMPORT ML MODULES

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report,roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.pipeline import Pipeline

# SEPERATE LABEL AND  FEATURE

In [ ]:
X = data['v2']
y = data['v1'].astype(int)

# CREATE MACHINE LEARNING PIPELINE

In [ ]:
pipeline = Pipeline([
    ("vectorizer", TfidfVectorizer(
        stop_words= "english",
        lowercase= True,
        max_features= 5000,
        ngram_range=(1,20),
        min_df= 2,
        max_df= 0.95,
        analyzer="char_wb"
    )),
    ("model", LogisticRegression(
        max_iter=1000,
        C=0.5,
        class_weight="balanced"
    ))
])

# SPLIT THE DATA

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, 
                                                    test_size= 0.2, 
                                                    random_state= 42,
                                                    stratify= y)
X_test_text = X_test.copy()

# TRAINING THE MODEL

In [ ]:
pipeline.fit(X_train, y_train)
#* This is important because the vocabulary should be learned only from the training data.

c:\Users\EYAN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:549: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char_wb', max_df=0.95,
                                 max_features=5000, min_df=2,
                                 ngram_range=(1, 20), stop_words='english')),
                ('model',
                 LogisticRegression(C=0.5, class_weight='balanced',
                                    max_iter=1000))])

# MAKE PREDICTIONS

In [ ]:
predictions = pipeline.predict(X_test)

# SHOW THE METRICS AND ANALYZE WHAT TO IMPROVE

In [ ]:
print("Accuracy:", accuracy_score(y_test, predictions))
print("Precision:", precision_score(y_test, predictions))
print("Recall:", recall_score(y_test, predictions))
print("F1:", f1_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))
auc = roc_auc_score(y_test, predictions)

print("ROC AUC:", auc)

Accuracy: 0.9901345291479821
Precision: 0.9726027397260274
Recall: 0.9530201342281879
F1: 0.9627118644067797
[[962   4]
 [  7 142]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       966
           1       0.97      0.95      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

ROC AUC: 0.9744396737393527

# ADJUSTED THE NGRAM_RANGE = 1,5 AND THE FALSE NEGATIVES GO FROM 11 TO 7

## PRINTING THE 5 FALSE NEGATIVES FOR ANALYSIS

In [ ]:
results = pd.DataFrame({
    "message": X_test_text,
    "actual": y_test,
    "predicted": predictions
})

false_negatives = results[
    (results["actual"] == 1) &
    (results["predicted"] == 0)
]

print(false_negatives.to_string())

                                                                                                                                                                                    message  actual  predicted
3358                                                                                                         Sorry I missed your call let's talk when you have the time. I'm on 07090201529       1          0
5449                                                                                                                 Latest News! Police station toilet stolen, cops have nothing to go on!       1          0
1429                                                                                                                For sale - arsenal dartboard. Good condition but no doubles or trebles!       1          0
2821                               ROMCAPspam Everyone around should be responding well to your presence since you are so warm and outgoing. You are bringing in a real breath of sunshine.       1          0
750                                                                                  Do you realize that in about 40 years, we'll have thousands of old ladies running around with tattoos?       1          0
3300                                                                                                                                               RCT' THNQ Adrian for U text. Rgds Vatian       1          0
2246  Hi ya babe x u 4goten bout me?' scammers getting smart..Though this is a regular vodafone no, if you respond you get further prem rate msg/subscription. Other nos used also. Beware!       1          0